[project]
name = "neovim-github"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yossef Moftah", email = "yossefmoftah000@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
neovim-github = "neovim_github:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
