[project]
name = "neovim-github"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yossef Moftah", email = "yossefmoftah000@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.142.2",
    "torch>=2.14.1",
    "transformers>=5.18.0",
    "uvicorn>=0.54.0",
]

[project.scripts]
neovim-github = "neovim_github:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
